---
# Mandatory changes
cnx_component_pack_ingress:                      cnx65-cp.stoeps.home
cnx_application_ingress:                         cnx65.stoeps.home

# Usernames and password for eventual customization. Shown here are default usernames and password. Change it to customize it

was_username:                                    wasadmin
was_password:                                    password

ldap_userid:                                     jjones
ldap_nr_of_users:                                100
ldap_user_password:                              password
ldap_user_admin_password:                        password

ihs_username:                                    ihsadmin
ihs_password:                                    password

connections_admin:                               jjones1

db_password:                                     password
db_concord_password:                             password

docs_username:                                   docsuser
docs_password:                                   password
sudo_group:                                      wheel

# Non-mandatory changes

# Type of HCL Connections deployment: small (default), medium and large.
cnx_deploy_type:                                 medium
ldap_user_mail_domain:                           stoeps.home

db2_download_location:                           "http://{{ groups['installer'][0] }}:8081"
tdi_download_location:                           "http://{{ groups['installer'][0] }}:8081"
connections_wizards_download_location:           "http://{{ groups['installer'][0] }}:8081"
iim_repository_url:                              "http://{{ groups['installer'][0] }}:8081"
was_repository_url:                              "http://{{ groups['installer'][0] }}:8081"
was_fixes_repository_url:                        "http://{{ groups['installer'][0] }}:8081"
ihs_repository_url:                              "http://{{ groups['installer'][0] }}:8081"
ihs_fixes_repository_url:                        "http://{{ groups['installer'][0] }}:8081"
cnx_docs_download_location:                      "http://{{ groups['installer'][0] }}:8081"
cnx_repository_url:                              "http://{{ groups['installer'][0] }}:8081"
component_pack_download_location:                "http://{{ groups['installer'][0] }}:8081"

# Falling back to the defaults for Connections 6.5.0.1
iim_bin_file:                                    "agent.installer.linux.gtk.x86_64_1.9.1003.20200730_2125.zip"
iim_version:                                     "1.9.1003.20200730_2125"

# The next two variables are fixing IBM Java version to one distributed with FP 16
java_version:                                    "8.0.5037.20190801_0015"
java_files:                                      { 'file_name': '8.0.5.37-WS-IBMWASJAVA-Linux.zip' }

# The variables below are specifying the specific version of FP16 and files needed
# to install it. Those files live in the repositories mentioned above.
was_fp_version:                                  "8.5.5016.20190801_0951"
was_fp_files:
  - { file_name: 8.5.5-WS-WASSupplements-FP016-part1.zip }
  - { file_name: 8.5.5-WS-WASSupplements-FP016-part2.zip }
  - { file_name: 8.5.5-WS-WASSupplements-FP016-part3.zip }

ihs_version:                                     "8.5.5016.20190801_0951"
ihs_fp_files:
  - { file_name: 8.5.5-WS-WASSupplements-FP016-part1.zip }
  - { file_name: 8.5.5-WS-WASSupplements-FP016-part2.zip }
  - { file_name: 8.5.5-WS-WASSupplements-FP016-part3.zip }

cnx_updates_enabled:                             True

dmgr_hostname:                                   "{{ hostvars[groups['dmgr'][0]]['inventory_hostname'] }}"

smtp_hostname:                                   localhost

connections_admin_password:                      "{{ ldap_user_admin_password }}"

db_username:                                     LCUSER
db_concord_username:                             docsuser
db_hostname:                                     "{{ hostvars[groups['db_servers'][0]]['inventory_hostname'] }}"
db_port:                                         50000
db_jdbc_file:                                    /opt/IBM/db2/V11.1/java
db_docs_jdbc_file:                               "{{ db_jdbc_file }}"
db_type:                                         DB2
db_version:                                      6.5
setup_db2_jdbc:                                  True

cnx_docs_package_name:                           HCL_Docs_v201.zip

# cnx_force_repopulation:                          True

cnx_enable_moderation:                           true
cnx_enable_invite:                               true

enable_prometheus_jmx_exporter:                  True

ifix_apar:                                       CFix.65CR1.2109
cnx_ifix_installer:                              HCL_Connections_6.5_updateInstaller_2104.zip
ifix_file:                                       CFix.65CR1.2109-IC6.5.0.0_CR1-Common-Fix.jar
cnx_package:                                     HCL_Connections_6.5_lin.tar
connections_wizards_package_name:                HCL_Connections_6.5_wizards_lin_aix.tar
cnx_major_version:                               6
elasticsearch_default_version:                   5

setup_docker_registry:                           true
component_pack_package_name:                     ComponentPack_6.5.0.1.zip

enable_pod_auto_scaling:                         false

#setup_installation:                              false
#setup_images:                                    false
#setup_credentials:                               false
#setup_psp:                                       false
#setup_connections_volumes:                       false
#setup_bootstrap:                                 false
#setup_connections_env:                           false
#setup_infrastructure:                            false
#setup_customizer:                                false
setup_elasticsearch:                             true
setup_elasticsearch7:                            false
setup_ingress:                                   true
setup_community_ingress:                         false
setup_teams:                                     false
setup_tailored_exp:                              false
#setup_orientme:                                  false
setup_elasticstack:                              false
#setup_sanity:                                    false
setup_kudosboards:                               false
setup_outlook_addin:                             false
#enable_es_metrics:                               false
enable_gk_flags:                                 false
setup_ms_teams_extensions:                       false
#skip_configure_redis:                            True

kubernetes_version:                              1.17.2
helm_version:                                    2.17.0

kudos_boards_licence:                            "PASTE_YOUR_LICENCE_KEY_HERE"

docker_registry_url:                             "{{ hostvars[groups['docker_registry'][0]]['inventory_hostname'] }}:5000"
load_balancer_dns:                               "{{ hostvars[groups['k8s_load_balancers'][0]]['inventory_hostname'] }}"
ic_internal:                                     "{{ hostvars[groups['ihs_servers'][0]]['inventory_hostname'] }}"
frontend_fqdn:                                   "{{ cnx_application_ingress }}"
frontend_domain:                                 "{{ cnx_application_ingress.split('.')[1:] | join('.') }}"
db_server:                                       "{{ db_hostname }}"
db_server_user:                                  "{{ db_username }}"
db_server_password:                              "{{ db_password }}"

setup_connections_docs:                          true
setup_connections_wizards:                       true

docs_shared_storage_type:                        nfs
docs_data_remote_path:                           /nfs65/docs_data
docs_data_local_path:                            /mnt/docs_data

viewer_shared_storage_type:                      nfs
viewer_data_remote_path:                         /nfs65/viewer_data
viewer_data_local_path:                          /mnt/viewer_data

cnx_shared_storage_type:                         nfs
cnx_data_remote_path:                            /nfs65/data/shared
cnx_data_local_path:                             /mnt/cnx_data

cnx_data_path_on_cnx_server:                     /opt/cnxshared

docs_url:                                        "{{ cnx_application_ingress }}"

#force_destroy_db2:                               True
#force_destroy_ihs:                               False
#force_destroy_websphere:                         False
#force_destroy_kubernetes:                        False
