#!/bin/bash
# Import script generated by test_user_generator.py

echo "Starting LDAP import..."
echo "Make sure your OpenLDAP server is running"

# Check if ldapadd is available
if ! command -v ldapadd &> /dev/null; then
    echo "Error: ldapadd not found. Install openldap-client package."
    exit 1
fi

# Import users
echo "Importing base structure..."
ldapadd -x -D "cn=admin,dc=stoeps,dc=home" -w adminpassword -f test_users.ldif

if [ $? -eq 0 ]; then
    echo "✅ Import successful!"
    echo "Total users imported: 2500"
    echo ""
    echo "To search users: ldapsearch -x -b 'ou=users,dc=stoeps,dc=home'"
    echo "To delete all users: ldapdelete -x -D 'cn=admin,dc=stoeps,dc=home' -w adminpassword -r 'ou=users,dc=stoeps,dc=home'"
else
    echo "❌ Import failed. Check LDAP server configuration."
fi
