---
- name: Install epel
  import_playbook: playbooks/epel.yml

- name: Install Connections
  import_playbook: playbooks/cnx.yml
    # - name: Cleanup
    #   import_playbook: playbooks/hcl/cleanup/cleanup-db2.yml

    # - name: Install Connections and prerequisits
    #   import_playbook: playbooks/setup-trial-environment.yml

    # - name: Setup Component Pack
    #   import_playbook: playbooks/hcl/setup-component-pack.yml
    #
    # - name: Setup Connections
    # import_playbook: playbooks/hcl/setup-connections-ifix.yml
    
