[installer]
10.0.22.1

[dns]
cnx-ns.stoeps.home

[dmgr]
cnx8-cs1417760-was.stoeps.home

[cnx_was_servers]
cnx8-cs1417760-was.stoeps.home

[conversion_servers]
cnx8-cs1417760-was.stoeps.home

[viewer_servers]
cnx8-cs1417760-was.stoeps.home

[docs_servers]
cnx8-cs1417760-was.stoeps.home

[ihs_servers]
cnx8-cs1417760-was.stoeps.home

[db2_servers]
cnx8-cs1417760-db.stoeps.home

[ldap_servers]
cnx-ds.stoeps.home

[k8s_masters]

[k8s_workers]

[k8s_admin]

[k8s_load_balancers]
cnx8-cs1417760.stoeps.home

[component_pack_master]

[was_servers:children]
cnx_was_servers

[docker_registry:children]

[db_servers:children]
db2_servers

[nfs_servers]
cnx8-cs1417760-nfs.stoeps.home

[nfs_servers:children]
dmgr
was_servers

[prometheus_node_exporter:children]
