download_location_host: 10.0.11.1
download_location_port: 8081
# Download location of DB2 and the licence file
db2_download_location: "http://{{ download_location_host }}:{{ download_location_port }}/"

# Download location of TDI
tdi_download_location: "{{ download_location_host }}:{{ download_location_port }}/"

# Download location of Connections Wizards for DB population
db2_wizards_download_location: "{{ download_location_host }}:{{ download_location_port }}/"

# Download location for IBM Installation manager
iim_repository_url: "http://{{ download_location_host }}:{{ download_location_port }}/"

# Download location for IBM WebSphere ND & IBM Java
was_repository_url: "http://{{ download_location_host }}:{{ download_location_port }}/"

# Download location of IBM WAS ND Fixpack 18
was_fixes_repository_url: "http://{{ download_location_host }}:{{ download_location_port }}/"

# Download location of IBM HTTP Server
ihs_repository_url: "http://{{ download_location_host }}:{{ download_location_port }}/"

# Download location of IBM HTTP Server fixpacks
ihs_fixes_repository_url: "http://{{ download_location_host }}:{{ download_location_port }}/"

# Download location of HCL Connections Docs 2.0.1
cnx_docs_download_location: "http://{{ download_location_host }}:{{ download_location_port }}/"

# Download location for HCL Connections zip file. Used by Connections installation and TDI to get tdisol archive.
cnx_repository_url: "{{ download_location_host }}:{{ download_location_port }}/"

was_files:
  - { file_name: CIK2HML.zip, check_sum: b1333962ba4b25c8632c7e4c82b472350337e99febac8f70ffbd551ca3905e83 }
  - { file_name: CIK2JML.zip, check_sum: b73ae070656bed6399a113c2db9fb0abaf5505b0d41c564bf2a58ce0b1e0dcd2 }
  - { file_name: CIK2IML.zip, check_sum: 440b7ed82089d43b1d45c1e908bf0a1951fed98f2542b6d37c8b5e7274c6b1c9 }
  
ihs_files:
  - { file_name: CIK1VML.zip, check_sum: d63c59de4a5548e3d26e71fefb76193d41ac7585bc450c1e504287e0a6f746c9 }
  - { file_name: CIK1WML.zip, check_sum: ac00e7ab43cc528fe7f3ccd69aeb6564a2e738e7bc6e30e71fd2e0d4bd64f39e }
  - { file_name: CIK1XML.zip, check_sum: 94e3d9b70b139ad5fa0578da6857b295c5d2370c1b6ecb544c1e5757406fec90 }