---
# defaults file for mongo5
tmp_dir: /opt/HCL/Binaries
mongo:
  img:
    registry: hclcr.io/cnx
    name: middleware-mongodb5
    tag: 20240628-112447
    complete: "{{ mongo.img.registry }}/{{ mongo.img.name }}:{{ mongo.img.tag }}"
  tar: "middleware-mongodb5_{{ mongo.img.tag }}.tar"
