---
# tasks file for mongo5
- name: Create tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Create containers directory
  ansible.builtin.file:
    state: directory
    path: "{{ tmp_dir }}"
    mode: '755'
    owner: ansible
    group: ansible
  become: true
  when:
    - inventory_hostname == groups['k8s_masters'][0]

- name: Create containers directory
  ansible.builtin.file:
    state: directory
    path: "{{ tmp_dir }}/connections-mongo5"
    mode: '755'
    owner: ansible
    group: ansible
  become: true
  when:
    - inventory_hostname != groups['k8s_masters'][0]

# Clone Repository
- name: Build Mongo 5 image and copy to controller
  when:
    - inventory_hostname == groups['k8s_masters'][0]
  block:
    - name: Clone connections-mongo5
      ansible.builtin.git:
        repo: https://github.com/HCL-TECH-SOFTWARE/connections-mongo5.git
        dest: "{{ tmp_dir }}/connections-mongo5"

    - name: Install Docker
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Start docker
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      become: true
      loop:
        - docker.socket
        - docker

    - name: Build Mongo5 image
      ansible.builtin.shell: |
        set -e
        docker build --no-cache --tag {{ mongo.img.complete }} -f Dockerfile .
        docker save -o {{ mongo.tar }} {{ mongo.img.complete }}
        chown ansible:ansible {{ mongo.tar }}
      args:
        chdir: "{{ tmp_dir }}/connections-mongo5"
      become: true

    - name: Copy image to Controller
      ansible.builtin.fetch:
        src: "{{ tmp_dir }}/connections-mongo5/{{ mongo.tar }}"
        dest: "/tmp/{{ mongo.tar }}"
        flat: true

    - name: Stop docker
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      become: true
      loop:
        - docker.socket
        - docker

- name: Copy image from Controller
  ansible.builtin.copy:
    src: "/tmp/{{ mongo.tar }}"
    dest: "{{ tmp_dir }}/connections-mongo5/{{ mongo.tar }}"
    mode: '644'
  when:
    - inventory_hostname != groups['k8s_masters'][0]

- name: Cleanup controller
  ansible.builtin.file:
    name: "{{ tmp_dir }}/connections-mongo5/{{ mongo.tar }}"
    state: absent
  delegate_to: localhost

- name: Import Mongo5 image to containerd
  ansible.builtin.shell: |
    set -e
    ctr -n=k8s.io image import --digests=true {{ mongo.tar }}
  args:
    chdir: "{{ tmp_dir }}/connections-mongo5"
  become: true

- name: Tag imported image
  ansible.builtin.shell: |
    set -e
    DATE=$(date +"%Y-%m-%d")
    MONGO_IMG=$(ctr  -n=k8s.io images ls | grep import-${DATE} | awk '{print $1}' | tail -1)
    ctr -n=k8s.io image tag $MONGO_IMG {{ mongo.img.complete }}
  register: image_version
  become: true
  when:
    - inventory_hostname != groups['k8s_masters'][0]


# Install buildah

# Create mongo5 image

# Tag image

# Copy image to nodes
